[project]
authors = ["FuelStreams Team"]
entry = "main.sw"
license = "Apache-2.0"
name = "fuel_streams"
version = "0.1.0"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", tag = "v0.65.1" }

[build-profile.release]
print-finalized-asm = false
print-intermediate-asm = false
print-ir = false
terse = false

[patch.std]
std = { git = "https://github.com/FuelLabs/sway", tag = "v0.65.1" } 